### PR TITLE
Fix ndb_json.loads('null')

### PR DESCRIPTION
**Pull request by mhluongo**
Use a custom `JSONDecoder` to avoid bugs decoding top-level nulls,
ints, strings, etc, and have better parity with `json.loads()`

### CODE REVIEW

**Comment by erichiggins** [comment]
Thanks for putting this PR together, @mhluongo !  Would you mind adding a unit test to demonstrate the issue that this change fixes?

**Comment by mhluongo** [comment]
Sure! Nice response time btw :)

**Comment by mhluongo** [comment]
It looks like Travis isn't running these tests?

**Comment by erichiggins** [comment]
Hm, that's strange.

**Comment by erichiggins** [comment]
At first glance, I don't see an obvious reason for why they aren't being run, do you?

**Comment by mhluongo** [comment]
Nothing's jumping out at me. When I use `nose` I typically run that instead of relying on `setup.py`\- might be worth a try

**Comment by erichiggins** [comment]
Want to try that in this PR?

**Comment by mhluongo** [comment]
Looks like nose skips executable files.

One of my tests had an issue (apparently NaN != NaN in Python?) but are otherwise good. Looks like there's a legacy test failing as well.

**Comment by erichiggins** [comment]
Wow, that's weird. Definitely seems to be the root cause though. I'll put together a patch to fix that and my other test so that this PR is unblocked. Thanks again!

**Comment by erichiggins** [comment]
Ok, I've merged the necessary changes that should unblock you. One thing to note though -- PRs should be merged into the `develop` branch instead of `master`. I think I have the wrong default on the repo in GitHub, so I'll need to correct that.

**Comment by mhluongo** [comment]
@erichiggins do you want this merged to `develop` or `master`? Note https://github.com/erichiggins/gaek/pull/9 was merged into `master` and will need to be merged back into this branch.

**Comment by erichiggins** [comment]
@mhluongo Yeah, I definitely moved too fast and messed that up. I just merged the changes back into `develop` so please merge into that branch instead of `master`. Sorry for the mix-up on my end and confusion.

**Comment by erichiggins** [comment]
@mhluongo Checking in to see if you'd still like to get this merged. Thanks again for the contribution!

**Comment by erichiggins** [comment]
I've created #13 to resolve the base-branch issues. Feel free to review if you're still interested.

**Pull request closed without merging**
